name: 02 Workflow Events
on: 
  workflow_dispatch:
    
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Events
        run: echo "i have been trigged by ${{github.event_name}} event"