name: 05 - 01 Event Filter and Activity Types

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a PR is opened or synchronize AND base branch is MAIN"
